export type PoetryBookTab = 'poems' | 'powers';

export const POETRY_BOOK_LABELS = {
  title: 'Собрание стихов',
  urlPath: 'volodka://poetry',
  headerCount: (collected: number, total: number) => `${collected} из ${total} найдено`,
  headerTagline: 'Стих — это сила',
  tabPoems: 'Стихи',
  tabPowers: 'Способности',
  tabPoemsAria: 'Вкладка стихов',
  tabPowersAria: 'Вкладка поэтических способностей',
  backToList: 'Назад к списку',
  prevPoem: 'Пред.',
  nextPoem: 'След.',
  pageNumber: (page: number, total: number) => `— ${page} / ${total} —`,
  tableOfContents: '— Оглавление —',
  mainPoemsSection: 'Стихи Владимира',
  hiddenPoemsSection: 'Скрытые стихи',
  lockedSection: 'Ещё не найдено',
  lockedMore: (count: number) => `...и ещё ${count}`,
  emptyPoemsTitle: 'Стихотворения ещё не найдены',
  emptyPoemsHint: 'Исследуйте мир, и стихи откроются вам',
  emptyPowersTitle: 'Способности ещё не открыты',
  emptyPowersHint: 'Собирайте стихи, чтобы получить поэтические способности',
  powersReadyCount: (ready: number, total: number) => `${ready} из ${total} готово`,
  powersUnlockedCount: (unlocked: number, total: number) => `${unlocked} из ${total} открыто`,
  marginNoteHeading: '— на полях, почерком Володьки —',
  poemViewRegion: (title: string) => `Стих: ${title}`,
  poemListRegion: 'Список собранных стихов',
  powersListRegion: 'Список поэтических способностей',
  selectPoemAria: (title: string) => `Открыть стих «${title}»`,
  lockedPoemAria: 'Стих ещё не найден',
  activatePower: 'Активировать способность',
  activatePowerShort: 'Активировать',
  activatePowerAria: (name: string) => `Активировать способность «${name}»`,
  activating: 'Активация...',
  cooldown: (seconds: number) => `Перезарядка: ${seconds}с`,
  powerReady: 'Готово',
  powerFromPoem: (title: string) => `Из: «${title}»`,
  typewriterLive: (title: string) => `Текст стиха «${title}»`,
} as const;

/** Display labels for poem theme tags (keys match poem data). */
export const POEM_THEME_LABELS: Record<string, string> = {
  смерть: 'смерть',
  любовь: 'любовь',
  отчаяние: 'отчаяние',
  надежда: 'надежда',
  коррупция: 'коррупция',
  память: 'память',
  культура: 'культура',
  путь: 'путь',
  душа: 'душа',
  судьба: 'судьба',
  одиночество: 'одиночество',
  рождество: 'рождество',
  дружба: 'дружба',
  море: 'море',
  поэзия: 'поэзия',
  ирония: 'ирония',
  детство: 'детство',
  творчество: 'творчество',
  космос: 'космос',
  город: 'город',
  вечность: 'вечность',
  звёзды: 'звёзды',
  мечта: 'мечта',
  прощание: 'прощание',
  добро: 'добро',
  клевета: 'клевета',
  прощение: 'прощение',
  семья: 'семья',
  шут: 'шут',
  лицемерие: 'лицемерие',
  разрушение: 'разрушение',
  альтруизм: 'альтруизм',
};

export const POEM_TYPEWRITER_CHAR_DELAY_MS = 40;
export const POEM_POWER_JUST_USED_MS = 2000;
