/**
 * AUTO-GENERATED by scripts/rpm-npc-import.mjs — do not edit manually.
 * Registry of RPM NPC GLB public URLs confirmed on disk after import.
 * Empty until `npm run assets:rpm-import` stages avatars (Sprint 2 pipeline).
 * Regenerate: npm run assets:rpm-import -- --apply-all
 */
export const RPM_NPC_GLB_URLS_ON_DISK: readonly string[] = [];
