import type { SceneDefinition } from '@/shared/types/sceneDefinition';
import type { ExtensionSceneId } from '@/config/sceneIds';

/** Additional AAA narrative locations — visuals inherited via sceneInheritance.ts */
export const EXTENSION_SCENE_DEFINITIONS = {
  chk_campfire_night: {
    id: 'chk_campfire_night',
    name: 'Костёр ЧК — ночь',
    dimensions: [24, 4, 22],
    type: 'outdoor',
    hasCeiling: false,
    defaultSpawn: [0, 0.01, 4],
    defaultSpawnRotation: 0,
    characterModelScale: 1.0,
    locomotionScale: 1.1,
    doorways: [{ id: 'campfire_to_forest', position: [0, 1, 10], width: 2.0, height: 2.5 }],
    exits: [
      {
        id: 'campfire_to_forest',
        targetScene: 'chk_forest_zorge',
        position: [0, 1, 10],
        spawnPosition: [0, 0.01, 6],
        spawnRotation: 0,
        label: '→ Лес Зорге',
        doorwayId: 'campfire_to_forest',
      },
    ],
    floors: [{ type: 'cuboid', size: [12, 0.05, 11], position: [0, -0.05, 0], footstepMaterial: 'grass' }],
    walls: [],
    obstacles: [
      { type: 'cuboidObstacle', size: [0.5, 0.5, 0.5], position: [0, 0.5, -2], footstepMaterial: 'metal' },
    ],
    ceilings: [],
    visualComponent: 'ChkForestVisual',
    lights: [
      { position: [0, 1.5, -2], intensity: 3.4, color: '#ff7722', distance: 16 },
      { position: [-3, 3, 2], intensity: 0.85, color: '#5577bb', distance: 22 },
      { position: [4, 2.5, -4], intensity: 0.45, color: '#334455', distance: 18 },
    ],
    ambientColor: '#1a2830',
    ambientIntensity: 0.45,
    groundColor: '#1e2a1a',
    fogEnabled: true,
    fog: { near: 8, far: 32 },
    ambience: { daySound: 'park', nightSound: 'corridor', transitionDuration: 2500 },
  },

  pier_evening: {
    id: 'pier_evening',
    name: 'Пирс — вечер',
    dimensions: [26, 4, 20],
    type: 'outdoor',
    hasCeiling: false,
    defaultSpawn: [0, 0.01, 5],
    defaultSpawnRotation: Math.PI,
    characterModelScale: 1.0,
    locomotionScale: 1.2,
    doorways: [{ id: 'pier_evening_to_park', position: [0, 1, 9], width: 2.0, height: 2.5 }],
    exits: [
      {
        id: 'pier_evening_to_park',
        targetScene: 'park_day',
        position: [0, 1, 9],
        spawnPosition: [11, 0.01, 7],
        spawnRotation: Math.PI,
        label: '→ Парк',
        doorwayId: 'pier_evening_to_park',
      },
    ],
    floors: [{ type: 'cuboid', size: [13, 0.05, 10], position: [0, -0.05, 0], footstepMaterial: 'wood' }],
    walls: [],
    obstacles: [
      { type: 'cuboidObstacle', size: [0.35, 0.5, 0.35], position: [0, 0.5, -2], footstepMaterial: 'metal' },
    ],
    ceilings: [],
    visualComponent: 'RiverPierVisual',
    lights: [
      { position: [0, 1.4, -2], intensity: 2.6, color: '#ffaa55', distance: 13 },
      { position: [-3.5, 1.2, 1], intensity: 1.1, color: '#ff8844', distance: 9 },
      { position: [0, 5, -12], intensity: 0.9, color: '#8899bb', distance: 30 },
    ],
    ambientColor: '#242838',
    ambientIntensity: 0.5,
    groundColor: '#2c2c38',
    fogEnabled: true,
    fog: { near: 10, far: 36, fogColor: '#1a1e2c' },
    ambience: { daySound: 'pier', nightSound: 'pier', transitionDuration: 2500 },
  },

  factory_roof: {
    id: 'factory_roof',
    name: 'Крыша завода',
    dimensions: [22, 6, 18],
    type: 'outdoor',
    hasCeiling: false,
    defaultSpawn: [0, 0.01, 0],
    defaultSpawnRotation: 0,
    characterModelScale: 1.0,
    locomotionScale: 1.0,
    doorways: [{ id: 'roof_to_factory', position: [0, 1, -8], width: 1.2, height: 2.2 }],
    exits: [
      {
        id: 'roof_to_factory',
        targetScene: 'abandoned_factory',
        position: [0, 1, -8],
        spawnPosition: [0, 0.01, 6],
        spawnRotation: Math.PI,
        label: '→ Цех',
        doorwayId: 'roof_to_factory',
      },
    ],
    floors: [{ type: 'cuboid', size: [11, 0.05, 9], position: [0, -0.05, 0], footstepMaterial: 'metal' }],
    walls: [],
    obstacles: [
      { type: 'cuboidObstacle', size: [0.6, 0.9, 0.6], position: [-3.5, 0.9, -3], footstepMaterial: 'metal' },
      { type: 'cuboidObstacle', size: [1.4, 0.35, 0.5], position: [3, 0.35, 2], footstepMaterial: 'metal' },
      { type: 'cuboidObstacle', size: [0.4, 1.2, 0.4], position: [2.5, 1.2, -4], footstepMaterial: 'metal' },
    ],
    ceilings: [],
    visualComponent: 'RooftopVisual',
    lights: [
      { position: [4, 3, -4], intensity: 1.45, color: '#ff4422', distance: 17 },
      { position: [-4, 3, 4], intensity: 0.95, color: '#aabbcc', distance: 15 },
      { position: [0, 2.2, 0], intensity: 0.7, color: '#ff8844', distance: 11 },
      { position: [-2, 4.5, -6], intensity: 0.45, color: '#6677aa', distance: 20 },
    ],
    ambientColor: '#242430',
    ambientIntensity: 0.46,
    groundColor: '#34343e',
    fogEnabled: true,
    fog: { near: 9, far: 34, fogColor: '#181820' },
    ambience: { daySound: 'rooftop', nightSound: 'rooftop', transitionDuration: 2000 },
  },

  library_basement: {
    id: 'library_basement',
    name: 'Подвал библиотеки',
    dimensions: [14, 3, 12],
    type: 'underground',
    hasCeiling: true,
    defaultSpawn: [0, 0.01, 4],
    defaultSpawnRotation: Math.PI,
    characterModelScale: 1.0,
    locomotionScale: 0.95,
    doorways: [{ id: 'basement_to_library', position: [0, 1, 6], width: 1.0, height: 2.2 }],
    exits: [
      {
        id: 'basement_to_library',
        targetScene: 'library_day',
        position: [0, 1, 6],
        spawnPosition: [0, 0.01, 0],
        spawnRotation: 0,
        label: '→ Библиотека',
        doorwayId: 'basement_to_library',
      },
    ],
    floors: [{ type: 'cuboid', size: [7, 0.05, 6], position: [0, -0.05, 0], footstepMaterial: 'concrete' }],
    walls: [],
    obstacles: [
      { type: 'cuboidObstacle', size: [0.4, 1.8, 1.2], position: [-3, 1.8, -2], footstepMaterial: 'wood' },
      { type: 'cuboidObstacle', size: [0.4, 1.8, 1.2], position: [3, 1.8, -2], footstepMaterial: 'wood' },
      { type: 'cuboidObstacle', size: [0.9, 0.55, 0.55], position: [0, 0.55, -3.2], footstepMaterial: 'wood' },
      { type: 'cuboidObstacle', size: [0.35, 1.1, 0.7], position: [-2.2, 1.1, 1.5], footstepMaterial: 'wood' },
    ],
    ceilings: [{ type: 'cuboid', size: [7, 0.1, 6], position: [0, 2.8, 0] }],
    visualComponent: 'LibraryBasementVisual',
    lights: [
      { position: [0, 2.2, -2], intensity: 1.55, color: '#ffdd99', distance: 11 },
      { position: [-2.5, 1.8, 1], intensity: 0.75, color: '#ccaa66', distance: 7 },
      { position: [2.4, 1.6, 0.5], intensity: 0.55, color: '#6688aa', distance: 6 },
    ],
    ambientColor: '#241e14',
    ambientIntensity: 0.36,
    groundColor: '#1a1610',
    fogEnabled: true,
    fog: { near: 2.5, far: 9.5, fogColor: '#100c08' },
    ambience: { daySound: 'library', nightSound: 'library', transitionDuration: 2000 },
  },

  city_square: {
    id: 'city_square',
    name: 'Центральная площадь',
    dimensions: [28, 4, 28],
    type: 'outdoor',
    hasCeiling: false,
    defaultSpawn: [0, 0.01, 0],
    defaultSpawnRotation: 0,
    characterModelScale: 1.0,
    locomotionScale: 1.1,
    doorways: [{ id: 'square_to_street', position: [0, 1, 13], width: 3.0, height: 2.5 }],
    exits: [
      {
        id: 'square_to_street',
        targetScene: 'street_night',
        position: [0, 1, 13],
        spawnPosition: [0, 0.01, 0],
        spawnRotation: 0,
        label: '→ Улица',
        doorwayId: 'square_to_street',
      },
    ],
    floors: [{ type: 'cuboid', size: [14, 0.05, 14], position: [0, -0.05, 0], footstepMaterial: 'concrete' }],
    walls: [],
    obstacles: [],
    ceilings: [],
    visualComponent: 'CitySquareVisual',
    lights: [
      { position: [0, 4, 0], intensity: 2.2, color: '#aaccff', distance: 26 },
      { position: [-8, 3.2, -6], intensity: 1.4, color: '#6688ff', distance: 16 },
      { position: [7, 3.0, 5], intensity: 1.1, color: '#ff6688', distance: 14 },
    ],
    ambientColor: '#222838',
    ambientIntensity: 0.48,
    groundColor: '#2e2e3a',
    fogEnabled: true,
    fog: { near: 12, far: 42, fogColor: '#121820' },
    ambience: { daySound: 'street', nightSound: 'street', transitionDuration: 2000 },
  },

  underground_bunker: {
    id: 'underground_bunker',
    name: 'Бункер Сопротивления',
    dimensions: [18, 4, 16],
    type: 'underground',
    hasCeiling: true,
    defaultSpawn: [0, 0.01, 6],
    defaultSpawnRotation: Math.PI,
    characterModelScale: 1.0,
    locomotionScale: 1.0,
    doorways: [{ id: 'bunker_to_street', position: [0, 1, 8], width: 1.4, height: 2.4 }],
    exits: [
      {
        id: 'bunker_to_street',
        targetScene: 'street_night',
        position: [0, 1, 8],
        spawnPosition: [4, 0.01, 2],
        spawnRotation: 0,
        label: '→ Улица',
        doorwayId: 'bunker_to_street',
        requiredFlag: 'resistance_bunker_found',
      },
    ],
    floors: [{ type: 'cuboid', size: [9, 0.05, 8], position: [0, -0.05, 0], footstepMaterial: 'concrete' }],
    walls: [],
    obstacles: [
      { type: 'cuboidObstacle', size: [1.2, 0.8, 0.6], position: [-3, 0.8, -2], footstepMaterial: 'metal' },
      { type: 'cuboidObstacle', size: [1.2, 0.8, 0.6], position: [3, 0.8, -2], footstepMaterial: 'metal' },
    ],
    ceilings: [{ type: 'cuboid', size: [9, 0.1, 8], position: [0, 3.2, 0] }],
    visualComponent: 'UndergroundBunkerVisual',
    lights: [
      { position: [0, 2.5, -3], intensity: 2.0, color: '#44ff88', distance: 13 },
      { position: [-4, 2.5, 2], intensity: 0.85, color: '#ff5544', distance: 9 },
      { position: [3.5, 2.2, 3], intensity: 0.55, color: '#6688aa', distance: 8 },
    ],
    ambientColor: '#152018',
    ambientIntensity: 0.38,
    groundColor: '#1c2220',
    fogEnabled: true,
    fog: { near: 3.5, far: 13, fogColor: '#0c1410' },
    ambience: { daySound: 'basement', nightSound: 'basement', transitionDuration: 2500 },
  },

  guild_mainframe: {
    id: 'guild_mainframe',
    name: 'Серверная гильдии',
    dimensions: [16, 4, 14],
    type: 'indoor',
    hasCeiling: true,
    defaultSpawn: [0, 0.01, 5],
    defaultSpawnRotation: Math.PI,
    characterModelScale: 1.0,
    locomotionScale: 0.95,
    doorways: [{ id: 'mainframe_to_office', position: [0, 1, 7], width: 1.2, height: 2.2 }],
    exits: [
      {
        id: 'mainframe_to_office',
        targetScene: 'office_day',
        position: [0, 1, 7],
        spawnPosition: [0, 0.01, 0],
        spawnRotation: 0,
        label: '→ Офис',
        doorwayId: 'mainframe_to_office',
      },
    ],
    floors: [{ type: 'cuboid', size: [8, 0.05, 7], position: [0, -0.05, 0], footstepMaterial: 'metal' }],
    walls: [],
    obstacles: [
      { type: 'cuboidObstacle', size: [0.5, 2.0, 1.0], position: [-3, 2, -1], footstepMaterial: 'metal' },
      { type: 'cuboidObstacle', size: [0.5, 2.0, 1.0], position: [3, 2, -1], footstepMaterial: 'metal' },
    ],
    ceilings: [{ type: 'cuboid', size: [8, 0.1, 7], position: [0, 3.2, 0] }],
    visualComponent: 'GuildMainframeVisual',
    lights: [
      { position: [0, 2.8, -3], intensity: 2.6, color: '#00ffaa', distance: 13 },
      { position: [-3, 2.2, 1], intensity: 1.1, color: '#4488ff', distance: 10 },
      { position: [3, 2.2, 1], intensity: 1.1, color: '#4488ff', distance: 10 },
    ],
    ambientColor: '#1a2830',
    ambientIntensity: 0.42,
    groundColor: '#222830',
    fogEnabled: true,
    fog: { near: 4, far: 12 },
    ambience: { daySound: 'office', nightSound: 'corridor', transitionDuration: 2000 },
  },

  zarema_room: {
    id: 'zarema_room',
    name: 'Комната Заремы',
    dimensions: [8, 3, 7],
    type: 'indoor',
    hasCeiling: true,
    defaultSpawn: [0, 0.01, 2],
    defaultSpawnRotation: 0,
    characterModelScale: 1.0,
    locomotionScale: 0.9,
    doorways: [{ id: 'zarema_to_corridor', position: [0, 1, 3.5], width: 1.0, height: 2.2 }],
    exits: [
      {
        id: 'zarema_to_corridor',
        targetScene: 'volodka_corridor',
        position: [0, 1, 3.5],
        spawnPosition: [2.5, 0.01, 0],
        spawnRotation: 0,
        label: '→ Коридор',
        doorwayId: 'zarema_to_corridor',
      },
    ],
    floors: [{ type: 'cuboid', size: [4, 0.05, 3.5], position: [0, -0.05, 0], footstepMaterial: 'wood' }],
    walls: [],
    obstacles: [
      { type: 'cuboidObstacle', size: [1.1, 0.45, 0.55], position: [-1.4, 0.45, -1.6], footstepMaterial: 'wood' },
      { type: 'cuboidObstacle', size: [0.45, 0.9, 0.45], position: [1.5, 0.9, -1.2], footstepMaterial: 'wood' },
    ],
    ceilings: [{ type: 'cuboid', size: [4, 0.1, 3.5], position: [0, 2.8, 0] }],
    visualComponent: 'ZaremaAlbertVisual',
    lights: [
      { position: [1, 1.5, -2], intensity: 2.15, color: '#ffcc88', distance: 8.5 },
      { position: [-1.2, 1.8, 0.5], intensity: 0.7, color: '#aa88cc', distance: 6 },
    ],
    ambientColor: '#342840',
    ambientIntensity: 0.68,
    groundColor: '#262430',
    fogEnabled: true,
    fog: { near: 3.5, far: 9.5, fogColor: '#1a1420' },
    ambience: { daySound: 'home', nightSound: 'home', transitionDuration: 2000 },
  },

  albert_backroom: {
    id: 'albert_backroom',
    name: 'Подсобка кафе',
    dimensions: [8, 3, 6],
    type: 'indoor',
    hasCeiling: true,
    defaultSpawn: [0, 0.01, 2],
    defaultSpawnRotation: 0,
    characterModelScale: 1.0,
    locomotionScale: 0.9,
    doorways: [{ id: 'backroom_to_cafe', position: [0, 1, 3], width: 1.0, height: 2.2 }],
    exits: [
      {
        id: 'backroom_to_cafe',
        targetScene: 'cafe_evening',
        position: [0, 1, 3],
        spawnPosition: [0, 0.01, 0],
        spawnRotation: 0,
        label: '→ Зал кафе',
        doorwayId: 'backroom_to_cafe',
      },
    ],
    floors: [{ type: 'cuboid', size: [4, 0.05, 3], position: [0, -0.05, 0], footstepMaterial: 'concrete' }],
    walls: [],
    obstacles: [
      { type: 'cuboidObstacle', size: [0.8, 0.9, 0.5], position: [-1.5, 0.9, -1], footstepMaterial: 'metal' },
    ],
    ceilings: [{ type: 'cuboid', size: [4, 0.1, 3], position: [0, 2.6, 0] }],
    visualComponent: 'AlbertBackroomVisual',
    lights: [
      { position: [0, 2.0, -1], intensity: 2.0, color: '#ffaa66', distance: 9 },
      { position: [1.5, 1.8, 0.5], intensity: 0.9, color: '#6688cc', distance: 7 },
    ],
    ambientColor: '#2a2030',
    ambientIntensity: 0.48,
    groundColor: '#1e1820',
    fogEnabled: true,
    fog: { near: 3, far: 9 },
    ambience: { daySound: 'cafe', nightSound: 'cafe', transitionDuration: 2000 },
  },

  /** Procedural AAA hero showcase — SDF world + character + post + audio sync */
  procedural_aaa: {
    id: 'procedural_aaa',
    name: 'Procedural AAA',
    dimensions: [28, 8, 28],
    type: 'outdoor',
    hasCeiling: false,
    defaultSpawn: [0, 0.01, 4],
    defaultSpawnRotation: Math.PI,
    characterModelScale: 1.0,
    locomotionScale: 1.15,
    doorways: [{ id: 'proc_aaa_to_street', position: [0, 1, 12], width: 2.0, height: 2.5 }],
    exits: [
      {
        id: 'proc_aaa_to_street',
        targetScene: 'street_night',
        position: [0, 1, 12],
        spawnPosition: [0, 0.01, 0],
        spawnRotation: 0,
        label: '→ Улица',
        doorwayId: 'proc_aaa_to_street',
      },
    ],
    floors: [{ type: 'cuboid', size: [14, 0.05, 14], position: [0, -0.05, 0], footstepMaterial: 'concrete' }],
    walls: [],
    obstacles: [],
    ceilings: [],
    visualComponent: 'ProceduralAaaVisual',
    lights: [
      { position: [4, 6, -4], intensity: 2.2, color: '#6688ff', distance: 28 },
      { position: [-5, 4, 3], intensity: 1.4, color: '#ff4488', distance: 22 },
      { position: [0, 3, 2], intensity: 0.9, color: '#aaccff', distance: 14 },
    ],
    ambientColor: '#1a2030',
    ambientIntensity: 0.42,
    groundColor: '#1c2230',
    fogEnabled: true,
    fog: { near: 6, far: 40, fogColor: '#2a3048' },
    ambience: { daySound: 'street', nightSound: 'street', transitionDuration: 2000 },
  },

  /** Forest clearing — natural, peaceful, mystical glade deep in the woods */
  forest_clearing: {
    id: 'forest_clearing',
    name: 'Лесная Поляна',
    dimensions: [20, 6, 20],
    type: 'outdoor',
    hasCeiling: false,
    defaultSpawn: [0, 0.01, 3],
    defaultSpawnRotation: 0,
    characterModelScale: 1.0,
    locomotionScale: 1.0,
    doorways: [{ id: 'clearing_to_forest', position: [0, 1, 9], width: 2.0, height: 2.5 }],
    exits: [
      {
        id: 'clearing_to_forest',
        targetScene: 'chk_forest_zorge',
        position: [0, 1, 9],
        spawnPosition: [0, 0.01, -4],
        spawnRotation: Math.PI,
        label: '→ Лес Зорге',
        doorwayId: 'clearing_to_forest',
      },
    ],
    floors: [{ type: 'cuboid', size: [10, 0.05, 10], position: [0, -0.05, 0], footstepMaterial: 'grass' }],
    walls: [],
    obstacles: [
      { type: 'cuboidObstacle', size: [0.6, 1.2, 0.6], position: [-3, 0.6, -2], footstepMaterial: 'wood' },
      { type: 'cuboidObstacle', size: [0.4, 0.8, 0.4], position: [2, 0.4, -3], footstepMaterial: 'wood' },
    ],
    ceilings: [],
    visualComponent: 'ChkForestVisual',
    lights: [
      { position: [0, 5, 0], intensity: 2.8, color: '#c8e8a0', distance: 20 },
      { position: [-4, 3, 3], intensity: 0.6, color: '#88aa66', distance: 12 },
      { position: [3, 2, -4], intensity: 0.4, color: '#aacc88', distance: 10 },
    ],
    ambientColor: '#2a3a20',
    ambientIntensity: 0.55,
    groundColor: '#1e2a1a',
    fogEnabled: true,
    fog: { near: 6, far: 28, fogColor: '#2a3a20' },
    ambience: { daySound: 'park', nightSound: 'corridor', transitionDuration: 3000 },
  },
} as const satisfies Record<ExtensionSceneId, SceneDefinition>;
