import type { NpcComposeRecipe } from '@/config/npcComposer/types';

/**
 * Unique modular compose recipes — each NPC gets a distinct slot combination.
 * Replaces 1:1 Quaternius rig cloning (albert ≠ kira, zarema ≠ tamara).
 */
export const NPC_COMPOSE_RECIPES: Record<string, NpcComposeRecipe> = {
  zarema: {
    npcId: 'zarema',
    title: 'Зарема',
    slots: {
      body: 'average_female',
      head: 'mature_female',
      hair: 'scarf_wrap',
      top: 'dress_long',
      bottom: 'hidden_dress',
      accessory: 'earring',
      prop: 'ladle',
    },
    rigRef: 'female_01',
    quaterniusPreset: 'Medieval',
    bodyLean: 0.03,
    defaultSilhouette: 'slim',
    headAccessoryFallback: 'scarf',
  },
  albert: {
    npcId: 'albert',
    title: 'Альберт',
    slots: {
      body: 'heavy_male',
      head: 'bearded_male',
      hair: 'gray_receding',
      top: 'tweed_jacket',
      bottom: 'slacks',
      accessory: 'glasses_scholarly',
      prop: 'book',
    },
    rigRef: 'male_02',
    quaterniusPreset: 'Suit',
    bodyLean: 0.04,
    defaultSilhouette: 'average',
    headAccessoryFallback: 'glasses',
  },
  solnysh: {
    npcId: 'solnysh',
    title: 'Солныш',
    slots: {
      body: 'slim_female',
      head: 'young_female',
      hair: 'ponytail',
      top: 'blouse',
      bottom: 'skirt_a_line',
      accessory: 'none',
      prop: 'phone',
    },
    rigRef: 'female_02',
    quaterniusPreset: 'Casual',
    bodyLean: 0.05,
    defaultSilhouette: 'slim',
  },
  cafe_barista: {
    npcId: 'cafe_barista',
    title: 'Бариста',
    slots: {
      body: 'average_male',
      head: 'young_male',
      hair: 'short_crop',
      top: 'barista_uniform',
      bottom: 'jeans',
      accessory: 'cyber_arm',
      prop: 'coffee_cup',
    },
    rigRef: 'male_04',
    quaterniusPreset: 'Worker',
    bodyLean: 0.04,
  },
  office_alexander: {
    npcId: 'office_alexander',
    title: 'Александр',
    slots: {
      body: 'average_male',
      head: 'mature_male',
      hair: 'short_crop',
      top: 'suit',
      bottom: 'slacks',
      accessory: 'badge',
      prop: 'none',
    },
    rigRef: 'male_05',
    quaterniusPreset: 'Suit',
    bodyLean: 0.03,
    defaultSilhouette: 'average',
  },
  office_dmitry: {
    npcId: 'office_dmitry',
    title: 'Дмитрий',
    slots: {
      body: 'slim_male',
      head: 'young_male',
      hair: 'hood',
      top: 'hoodie',
      bottom: 'pants_dark',
      accessory: 'glasses_round',
      prop: 'none',
    },
    rigRef: 'male_03',
    quaterniusPreset: 'Casual_Hoodie',
    bodyLean: 0.06,
    defaultSilhouette: 'slim',
  },
  maria: {
    npcId: 'maria',
    title: 'Виктория',
    slots: {
      body: 'slim_female',
      head: 'young_female',
      hair: 'ponytail',
      top: 'jacket_casual',
      bottom: 'jeans',
      accessory: 'none',
      prop: 'phone',
    },
    rigRef: 'female_03',
    quaterniusPreset: 'SciFi',
    bodyLean: 0.05,
  },
  chk_ru: {
    npcId: 'chk_ru',
    title: 'Ру',
    slots: {
      body: 'average_male',
      head: 'mature_male',
      hair: 'cap',
      top: 'jacket_casual',
      bottom: 'jeans',
      accessory: 'none',
      prop: 'none',
    },
    rigRef: 'male_06',
    quaterniusPreset: 'Adventurer',
    bodyLean: 0.05,
  },
  chk_based: {
    npcId: 'chk_based',
    title: 'Басед',
    slots: {
      body: 'heavy_male',
      head: 'mature_male',
      hair: 'short_crop',
      top: 'work_coat',
      bottom: 'work_pants',
      accessory: 'none',
      prop: 'wrench',
    },
    rigRef: 'male_07',
    quaterniusPreset: 'Worker',
    bodyLean: 0.05,
  },
  chk_smert: {
    npcId: 'chk_smert',
    title: 'Смерть',
    slots: {
      body: 'slim_female',
      head: 'young_female',
      hair: 'shoulder_length',
      top: 'cardigan',
      bottom: 'pants_dark',
      accessory: 'glasses_round',
      prop: 'book',
    },
    rigRef: 'female_04',
    quaterniusPreset: 'Formal',
    bodyLean: 0.03,
  },
  chk_stalker: {
    npcId: 'chk_stalker',
    title: 'Сталкер',
    slots: {
      body: 'slim_male',
      head: 'young_male',
      hair: 'hood',
      top: 'windbreaker',
      bottom: 'work_pants',
      accessory: 'none',
      prop: 'none',
    },
    rigRef: 'male_08',
    quaterniusPreset: 'Swat',
    bodyLean: 0.06,
  },
  chk_elis: {
    npcId: 'chk_elis',
    title: 'Элис',
    slots: {
      body: 'slim_female',
      head: 'young_female',
      hair: 'bun_dark',
      top: 'cardigan',
      bottom: 'skirt_a_line',
      accessory: 'glasses_round',
      prop: 'guitar',
    },
    rigRef: 'female_05',
    quaterniusPreset: 'Punk',
    bodyLean: 0.03,
  },
  chk_ritka: {
    npcId: 'chk_ritka',
    title: 'Ритка',
    slots: {
      body: 'slim_female',
      head: 'young_female',
      hair: 'shoulder_length',
      top: 'hoodie',
      bottom: 'pants_dark',
      accessory: 'earring',
      prop: 'guitar',
    },
    rigRef: 'female_06',
    quaterniusPreset: 'Casual',
    bodyLean: 0.04,
    headAccessoryFallback: 'earring',
  },
  maxim: {
    npcId: 'maxim',
    title: 'Максим',
    slots: {
      body: 'heavy_male',
      head: 'mature_male',
      hair: 'short_crop',
      top: 'windbreaker',
      bottom: 'work_pants',
      accessory: 'cyber_arm',
      prop: 'none',
    },
    rigRef: 'male_09',
    quaterniusPreset: 'Swat',
    bodyLean: 0.05,
    defaultSilhouette: 'heavy',
  },
  anya: {
    npcId: 'anya',
    title: 'Аня',
    slots: {
      body: 'slim_female',
      head: 'young_female',
      hair: 'short_crop',
      top: 'hoodie',
      bottom: 'pants_dark',
      accessory: 'glasses_round',
      prop: 'none',
    },
    rigRef: 'female_07',
    quaterniusPreset: 'SciFi',
    bodyLean: 0.04,
  },
  zeka: {
    npcId: 'zeka',
    title: 'Жека',
    slots: {
      body: 'average_male',
      head: 'elder_male',
      hair: 'cap',
      top: 'work_coat',
      bottom: 'work_pants',
      accessory: 'none',
      prop: 'wrench',
    },
    rigRef: 'male_10',
    quaterniusPreset: 'Farmer',
    bodyLean: 0.07,
  },
  baba_zina: {
    npcId: 'baba_zina',
    title: 'Баба Зина',
    slots: {
      body: 'elder_female_stooped',
      head: 'elder_female',
      hair: 'bun_gray',
      top: 'apron',
      bottom: 'work_pants',
      accessory: 'none',
      prop: 'soldering_iron',
    },
    rigRef: 'female_08',
    quaterniusPreset: 'Witch',
    bodyLean: 0.1,
    defaultSilhouette: 'average',
  },
  fisherman_trofim: {
    npcId: 'fisherman_trofim',
    title: 'Трофим',
    slots: {
      body: 'elder_male',
      head: 'elder_male',
      hair: 'cap',
      top: 'work_coat',
      bottom: 'work_pants',
      accessory: 'none',
      prop: 'fishing_rod',
    },
    rigRef: 'male_11',
    quaterniusPreset: 'Beach',
    bodyLean: 0.04,
  },
  kate: {
    npcId: 'kate',
    title: 'Катя',
    slots: {
      body: 'slim_female',
      head: 'young_female',
      hair: 'bun_dark',
      top: 'cardigan',
      bottom: 'pants_dark',
      accessory: 'glasses_round',
      prop: 'book',
    },
    rigRef: 'female_09',
    quaterniusPreset: 'Formal',
    bodyLean: 0.03,
  },
  office_colleague: {
    npcId: 'office_colleague',
    title: 'Коллега',
    slots: {
      body: 'average_male',
      head: 'young_male',
      hair: 'short_crop',
      top: 'jacket_casual',
      bottom: 'jeans',
      accessory: 'glasses_round',
      prop: 'none',
    },
    // Exclusive staged modular mesh — not office_dmitry / chk twins
    rigRef: 'male_01',
    quaterniusPreset: 'Casual_2',
    bodyLean: 0.04,
  },
  viktor: {
    npcId: 'viktor',
    title: 'Виктор',
    slots: {
      body: 'heavy_male',
      head: 'mature_male',
      hair: 'bald',
      top: 'suit',
      bottom: 'slacks',
      accessory: 'badge',
      prop: 'none',
    },
    rigRef: 'male_02',
    quaterniusPreset: 'King',
    bodyLean: 0.03,
  },
  kira: {
    npcId: 'kira',
    title: 'Кира',
    slots: {
      body: 'slim_female',
      head: 'mature_female',
      hair: 'shoulder_length',
      top: 'blouse',
      bottom: 'skirt_a_line',
      accessory: 'glasses_round',
      prop: 'none',
    },
    rigRef: 'female_01',
    quaterniusPreset: 'Soldier',
    bodyLean: 0.03,
  },
  boris: {
    npcId: 'boris',
    title: 'Борис',
    slots: {
      body: 'heavy_male',
      head: 'bearded_male',
      hair: 'gray_receding',
      top: 'work_coat',
      bottom: 'work_pants',
      accessory: 'none',
      prop: 'wrench',
    },
    rigRef: 'male_04',
    quaterniusPreset: 'Worker',
    bodyLean: 0.05,
  },
  tamara: {
    npcId: 'tamara',
    title: 'Тамара',
    slots: {
      body: 'average_female',
      head: 'mature_female',
      hair: 'bun_dark',
      top: 'cardigan',
      bottom: 'skirt_a_line',
      accessory: 'glasses_round',
      prop: 'book',
    },
    rigRef: 'female_02',
    quaterniusPreset: 'Witch',
    bodyLean: 0.03,
  },
  grisha: {
    npcId: 'grisha',
    title: 'Гриша',
    slots: {
      body: 'slim_male',
      head: 'young_male',
      hair: 'beanie',
      top: 'windbreaker',
      bottom: 'jeans',
      accessory: 'none',
      prop: 'none',
    },
    rigRef: 'male_06',
    quaterniusPreset: 'Punk',
    bodyLean: 0.05,
  },
  lena: {
    npcId: 'lena',
    title: 'Лена',
    slots: {
      body: 'slim_female',
      head: 'young_female',
      hair: 'hood',
      top: 'hoodie',
      bottom: 'pants_dark',
      accessory: 'none',
      prop: 'none',
    },
    rigRef: 'female_06',
    quaterniusPreset: 'Punk',
    bodyLean: 0.04,
  },
  sergey: {
    npcId: 'sergey',
    title: 'Сергей',
    slots: {
      body: 'average_male',
      head: 'mature_male',
      hair: 'short_crop',
      top: 'work_coat',
      bottom: 'work_pants',
      accessory: 'none',
      prop: 'wrench',
    },
    rigRef: 'male_09',
    quaterniusPreset: 'Worker',
    bodyLean: 0.04,
  },
  lyonya: {
    npcId: 'lyonya',
    title: 'Лёня',
    slots: {
      body: 'slim_male',
      head: 'young_male',
      hair: 'short_crop',
      top: 'hoodie',
      bottom: 'jeans',
      accessory: 'none',
      prop: 'none',
    },
    rigRef: 'male_04',
    quaterniusPreset: 'Casual_Hoodie',
    bodyLean: 0.05,
  },
  oleg: {
    npcId: 'oleg',
    title: 'Олег',
    slots: {
      body: 'heavy_male',
      head: 'mature_male',
      hair: 'short_crop',
      top: 'suit',
      bottom: 'slacks',
      accessory: 'badge',
      prop: 'none',
    },
    rigRef: 'male_05',
    quaterniusPreset: 'Suit',
    bodyLean: 0.03,
  },
};

export function listNpcComposeRecipeIds(): string[] {
  return Object.keys(NPC_COMPOSE_RECIPES);
}
