/**
 * Regenerate on-disk shipped flags for ASSET_MANIFEST entries.
 * Run after assets:bootstrap or assets:process so runtime skips missing GLBs.
 *
 * Usage: npm run assets:sync-shipped
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ASSET_MANIFEST } from '../src/config/assetManifest';
import { isManifestAssetPresentOnDisk } from './lib/assetDiskPresence.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = path.join(ROOT, 'src/config/assetManifestShipped.generated.ts');

function writeGenerated(flags: Record<string, boolean>): void {
  const entries = Object.entries(flags)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, onDisk]) => `  ${id}: ${onDisk ? 'true' : 'false'},`)
    .join('\n');

  const body = `/**
 * On-disk presence for manifest assets — regenerated by \`npm run assets:sync-shipped\`.
 * @generated — do not edit manually.
 */

/** Whether processed files exist under public/models/ for each manifest id. */
export const ASSET_DISK_SHIPPED: Readonly<Record<string, boolean>> = {
${entries}
};
`;
  writeFileSync(OUTPUT, body, 'utf8');
}

function main(): void {
  const flags: Record<string, boolean> = {};

  for (const [id, asset] of Object.entries(ASSET_MANIFEST)) {
    if (asset.shipped !== true) continue;
    flags[id] = isManifestAssetPresentOnDisk(ROOT, asset);
  }

  writeGenerated(flags);

  const present = Object.values(flags).filter(Boolean).length;
  const total = Object.keys(flags).length;
  console.log(`✓ Synced asset disk flags → ${path.relative(ROOT, OUTPUT)} (${present}/${total} on disk)`);
}

main();
